### ISSUE TITLE
Adding a couple more dependencies

### ISSUE THREAD

**Issue by mrazomej** [AddisonHowe/phys2ddm#7]
For my tutorial, I also used `seaborn` to improve my plots and `watermark` to generate at the end of the notebook a watermark on the version of the software used. It looks something like this:

```python
%load_ext watermark
%watermark -v -p numpy,scipy,pandas,matplotlib,seaborn
```

which prints the following:
```
Python implementation: CPython
Python version       : 3.10.14
IPython version      : 8.22.2

numpy     : 1.26.4
scipy     : 1.12.0
pandas    : 2.2.1
matplotlib: 3.8.3
seaborn   : 0.13.2
```

I think that every tutorial should include this for reproducibility.

Can these two dependencies be added to the `README.md` file?

**Comment by AddisonHowe** [comment]
I think that's a good idea. Thanks for sharing this! If you'd like to make the change to the README, go ahead. Otherwise I can when I get a chance.

**Comment by mrazomej** [comment]
@AnkitaRoychoudhury , I am just tagging you on this one for you to include it in your tutorials as well :-)
